### ISSUE TITLE
[IRobotManager.hpp] Think about more than mobile robots

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/yarp-devices#10]
[IRobotManager.hpp] Think about more than mobile robots.

Note that [current interface](https://github.com/asrob-uc3m/yarp-devices/blob/341a73c99f794567cf872485c04e159583a0f2f8/libraries/YarpPlugins/IRobotManager.hpp) was inspired on shooter `WASD + mouse`-like movements.

But perhaps we want a more generic interface, such as the long-term proposal of https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/148.

**Comment by PeterBowman** [comment]
I am tempted to replicate here the [*keyboardController* app](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/f1f4ec97a50ae98831d0003821059ac881fa468c/programs/keyboardController), currently a `ICartesianControl` client, in order to provide a means to control a robot/drone via the `IRobotManager` interface with a simple keyboard. By using a unique interface for manipulators and mobile robots, duplication would be avoided.

Anyway, I may create our own *keyboardController* here and give a try to some ideas laid out at https://github.com/robotology/QA/issues/289, then export (or migrate) to kinematics-dynamics.

**Comment by jgvictores** [comment]
Closing this because it makes no sense. In any case:

1. IRobotManager was always too broad. If we ever ended up with more kinds of robots, it should be decoupled (e.g. current `IRobotManager` become `IMobileRobotManager` or even `I2DMobileRobotManager`.
2. Next, we'd have input interfaces.
3. Best case, we'd have an independent mechanism that implements a (configurable) mapping ("glue") from (2) to (1).
